repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: 'v1.64.0'
  hooks:
    - id: checkov
    - id: terraform_fmt
    - id: terraform_validate
    # - id: terraform_tflint
    # - id: terraform_tfsec
