name: TFLint

on:
  pull_request:

jobs:
  tflint-serverless:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v1
        with:
          tflint_version: v0.34.1
      - name: Install Terraform plugins
        run: tflint --init

      - name: Lint Terraform files
        run: tflint -f junit > tflint_report.xml

      - name: Publish test report
        uses: mikepenz/action-junit-report@v2
        # Only run this step on failure
        if: ${{ failure() }}
        with:
          report_paths: cfn_lint_report.xml